### ISSUE TITLE
SAVEMATRIXSPORDER Doubled-up

### ISSUE THREAD

**Issue by LindsayBradford** [mattwatts/marxan3#1]
In SetOptions() of MarOpt_v300.c, SAVEMATRIXSPORDER is having its input data file value assigned to both sfname.savepuvspr and sfname.savematrixsporder (below):

``` C
rdsvar(fp,"SAVEMATRIXPUORDER",&(*fnames).savepuvspr,INTEGER,0,present);   
rdsvar(fp,"SAVEMATRIXSPORDER",&(*fnames).savematrixsporder,INTEGER,0,present);
```

**Comment by mattwatts** [comment]
After a closer look, this seems ok to me.

The first instruction is assigning SAVEMATRIXPUORDER to savepuvspr.

The second instruction is assigning SAVEMATRIXSPORDER to savematrixsporder.

Note the first is "PU" order, the second is "SP" order. Am I missing something?

**Comment by LindsayBradford** [comment]
ahh... brainfart.  Read both as exactly the same. Ignore this. :/
